<?php
/**
 * @author  IntoWebDevelopment <info@intowebdevelopment.nl>
 * @project SnelstartApiPHP
 */

namespace SnelstartPHP\Exception;

class SnelstartApiErrorException extends \RuntimeException
{
    /**
     * This contains a collection grouped by HTTP STATUS CODE => Resource => Message
     */
    const API_ERROR_EXCEPTIONS    =   [
        400 =>  [
            'VOR-0001' => "Verkooporder niet gevonden",
            'VOR-0002' => "De relatie is geen klant",
            'VOR-0003' => "De factuurrelatie is geen klant",
            'VOR-0004' => "De machtiging hoort niet bij deze klant",
            'VOR-0005' => "Bij een nieuwe verkooporder moet het veld ordernummer leeg zijn",
            'VOR-0006' => "Straat mag maximaal 50 karakters bevatten",
            'VOR-0007' => "Postcode mag maximaal 25 karakters bevatten",
            'VOR-0008' => "Plaats mag maximaal 50 karakters bevatten",
            'VOR-0009' => "Contactpersoon mag maximaal 50 karakters bevatten",
            'VOR-0010' => "LandId niet gevonden",
            'REL-0001' => "RelatieSoort mag niet 'geen' zijn",
            'REL-0002' => "RelatieSoort dient klant te bevatten indien aanmanen aan staat",
            'REL-0003' => "Krediettermijn mag niet kleiner dan -365 of groter dan 1000 zijn",
            'REL-0004' => "RelatieSoort dient klant te bevatten indien Factuurkorting aan staat",
            'REL-0006' => "KvkNummer is ongeldig",
            'REL-0007' => "Naam moet gevuld zijn",
            'REL-0008' => "Relatiecode reeds in gebruik",
            'REL-0009' => "Iban mag niet leeg zijn wanneer bankieren aan staat of incassosoort is 'geen'",
            'REL-0010' => "Bic is ongeldig",
            'REL-0011' => "Iban is ongeldig",
            'REL-0012' => "MobieleTelefoon mag maximaal 25 karakters bevatten",
            'REL-0013' => "Telefoon mag maximaal 25 karakters bevatten",
            'REL-0014' => "Relatiesoort dient leverancier te bevatten indien bankieren aan staat",
            'REL-0015' => "WebSiteUrl dient een geldig URL te zijn",
            'REL-0016' => "RelatieSoort dient klant te bevatten indien IncassoSoort gevuld is",
            'REL-0017' => "Factuurrelatie bestaat niet",
            'REL-0018' => "Factuurrelatie is geen klant",
            'REL-0020' => "VestigingsAdres.Straat mag maximaal 50 karakters bevatten",
            'REL-0021' => "VestigingsAdres.Postcode mag maximaal 25 karakters bevatten",
            'REL-0022' => "VestigingsAdres.Plaats mag maximaal 50 karakters bevatten",
            'REL-0023' => "VestigingsAdres.Contactpersoon mag maximaal 50 karakters bevatten",
            'REL-0025' => "Correspondentie.Straat mag maximaal 50 karakters bevatten",
            'REL-0026' => "Correspondentie.Postcode mag maximaal 25 karakters bevatten",
            'REL-0027' => "Correspondentie.Plaats mag maximaal 50 karakters bevatten",
            'REL-0028' => "Correspondentie.Contactpersoon mag maximaal 50 karakters bevatten",
            'REL-0029' => "AanmaningEmailVersturen.Email dient gevuld te zijn indien AanmaningEmailVersturen.ShouldSend aan staat",
            'REL-0030' => "AanmaningEmailVersturen.Email dient een geldig emailadres te zijn",
            'REL-0031' => "AanmaningEmailVersturen.CcEmail dient een geldig emailadres te zijn",
            'REL-0032' => "FactuurEmailVersturen.Email dient gevuld te zijn indien FactuurEmailVersturen.ShouldSend aan staat",
            'REL-0033' => "FactuurEmailVersturen.Email dient een geldig emailadres te zijn",
            'REL-0034' => "FactuurEmailVersturen.CcEmail dient een geldig emailadres te zijn",
            'REL-0038' => "BevestigingsEmailVersturen.Email dient gevuld te zijn indien BevestigingsEmailVersturen.ShouldSend aan staat",
            'REL-0039' => "BevestigingsEmailVersturen.Email dient een geldig emailadres te zijn",
            'REL-0040' => "BevestigingsEmailVersturen.CcEmail dient een geldig emailadres te zijn",
            'REL-0044' => "OfferteEmailVersturen.Email dient gevuld te zijn indien OfferteEmailVersturen.ShouldSend aan staat",
            'REL-0045' => "OfferteEmailVersturen.Email dient een geldig emailadres te zijn",
            'REL-0046' => "OfferteEmailVersturen.CcEmail dient een geldig emailadres te zijn",
            'REL-0047' => "Het ID in het url en het ID van de relatie in het request komen niet overeen",
            'REL-0048' => "RelatieSoort mag niet 'eigen' bevatten",
            'REL-0049' => "Klant heeft openstaande facturen",
            'REL-0050' => "Klant heeft openstaande verkooporders",
            'REL-0051' => "Klant is een factuurrelatie",
            'REL-0052' => "Klant wordt gebruikt voor inkooporders",
            'REL-0053' => "Leverancier heeft openstaande facturen",
            'REL-0054' => "Leverancier heeft openstaande inkooporders",
            'REL-0055' => "CorrespondentieAdres.LandId niet gevonden",
            'REL-0056' => "VestigingsAdres.LandId niet gevonden",
            'REL-0057' => "BtwNummer mag maximaal 50 karakters bevatten",
            'REL-0058' => "BtwNummer moet minimaal 2 karakters bevatten",
            'REL-0059' => "BtwNummer mag alleen cijfers en letters bevatten",
            'REL-0060' => "Indien een van de velden van VestigingsAdres gevuld is, meegegeven dienen alle velden gevuld zijn, uitgezonderd Contactpersoon",
            'REL-0061' => "Email dient een geldig emailadres te zijn.",
            'REL-0062' => "RelatieSoort dient klant te bevatten indien Kredietlimiet ingevuld is.",
            'REL-0063' => "Het ID dient leeg te zijn.",
            'REL-0064' => "RelatieSoort mag niet aangepast worden.",
            'REL-0065' => "RelatieSoort kan niet zowel 'klant' als 'leverancier' zijn.",
            'REL-0066' => "De input is incompleet of incorrect. Controleer of de json valide is en de juiste properties bevat.",
            'REL-0067' => "Deze leverancier kan niet worden verwijderd omdat deze intern door SnelStart wordt gebruikt.",
            'REL-0068' => "AanmaningEmailVersturen.Email bevat één of meerdere ongeldige emailadressen. U kunt meerdere emailadressen opgeven door ze te scheiden met een puntkomma(;).",
            'REL-0069' => "AanmaningEmailVersturen.Email mag maximaal 250 karakters bevatten",
            'REL-0070' => "AanmaningEmailVersturen.CcEmail bevat één of meerdere ongeldige emailadressen. U kunt meerdere emailadressen opgeven door ze te scheiden met een puntkomma(;).",
            'REL-0071' => "AanmaningEmailVersturen.CcEmail mag maximaal 250 karakters bevatten",
            'REL-0072' => "FactuurEmailVersturen.Email bevat één of meerdere ongeldige emailadressen. U kunt meerdere emailadressen opgeven door ze te scheiden met een puntkomma(;).",
            'REL-0073' => "FactuurEmailVersturen.Email mag maximaal 250 karakters bevatten",
            'REL-0074' => "FactuurEmailVersturen.CcEmail bevat één of meerdere ongeldige emailadressen. U kunt meerdere emailadressen opgeven door ze te scheiden met een puntkomma(;).",
            'REL-0075' => "FactuurEmailVersturen.CcEmail mag maximaal 250 karakters bevatten",
            'REL-0076' => "BevestigingsEmailVersturen.Email bevat één of meerdere ongeldige emailadressen. U kunt meerdere emailadressen opgeven door ze te scheiden met een puntkomma(;).",
            'REL-0077' => "BevestigingsEmailVersturen.Email mag maximaal 250 karakters bevatten",
            'REL-0078' => "BevestigingsEmailVersturen.CcEmail bevat één of meerdere ongeldige emailadressen. U kunt meerdere emailadressen opgeven door ze te scheiden met een puntkomma(;).",
            'REL-0079' => "BevestigingsEmailVersturen.CcEmail mag maximaal 250 karakters bevatten",
            'REL-0080' => "OfferteEmailVersturen.Email bevat één of meerdere ongeldige emailadressen. U kunt meerdere emailadressen opgeven door ze te scheiden met een puntkomma(;).",
            'REL-0081' => "OfferteEmailVersturen.Email mag maximaal 250 karakters bevatten",
            'REL-0082' => "OfferteEmailVersturen.CcEmail bevat één of meerdere ongeldige emailadressen. U kunt meerdere emailadressen opgeven door ze te scheiden met een puntkomma(;).",
            'REL-0083' => "OfferteEmailVersturen.CcEmail mag maximaal 250 karakters bevatten",
            'REL-0084' => "Email bevat één of meerdere ongeldige emailadressen. U kunt meerdere emailadressen opgeven door ze te scheiden met een puntkomma(;).",
            'REL-0085' => "Email mag maximaal 250 karakters bevatten",
            'KPL-0001' => "Kostenplaats niet gevonden",
            'KPL-0002' => "Dit id bestaat al",
            'KPL-0003' => "Het id is verplicht",
            'KPL-0004' => "De omschrijving is verplicht",
            'KPL-0005' => "De omschrijving mag maximaal 50 karakters bevatten",
            'KPL-0006' => "Het nummer is verplicht",
            'KPL-0007' => "Het nummer moet tussen 1 en 999999999 liggen",
            'KPL-0008' => "Dit nummer bestaat al",
            'KPL-0009' => "Er kan geen nonactieve kostenplaats worden gemaakt",
            'BOE-0001' => "Niet gevonden",
            'BOE-0002' => "Leverancier niet gevonden",
            'BOE-0003' => "Het Id is gevonden maar de relatie is geen leverancier",
            'BOE-0008' => "De grootboekrekening is verwijderd en staat op nonactief in de administratie",
            'BOE-0009' => "Het dagboek inkoop is verwijderd en staat op nonactief in de administratie",
            'BOE-0010' => "Het dagboek inkoop is niet gevonden",
            'BOE-0019' => "De kostenplaats is niet gevonden",
            'BOE-0021' => "Het factuurnummer bestaat al",
            'BOE-0022' => "Bij de opgegeven grootboekrekening is een kostenplaats is verplicht",
            'BOE-0023' => "Er zijn geen boekingsregels",
            'BOE-0024' => "Het dagboek kas is verwijderd en staat op nonactief in de administratie",
            'BOE-0025' => "Het dagboek kas is niet gevonden",
            'BOE-0026' => "De kostenplaats is verwijderd en staat op nonactief",
            'BOE-0027' => "Het afgedragen en ontvangen bedrag zijn beide ongelijk aan nul",
            'BOE-0028' => "Een regelbedrag is nul",
            'BOE-0029' => "Het formaat van de Ubl is niet geldig",
            'BOE-0031' => "De Ubl content mag niet leeg zijn",
            'BOE-0032' => "Ubl voldoet niet aan het schema",
            'BOE-0033' => "De boekdatum mag niet meer dan 5 jaar voor het huidig boekjaar liggen",
            'BOE-0036' => "Ongeldige munteenheid",
            'BOE-0037' => "Een grootboekrekening kon niet worden gevonden",
            'BOE-0038' => "De leverancier kon niet worden gevonden",
            'BOE-0039' => "De boeking is niet in balans",
            'BOE-0042' => "De boekdatum ligt in een geblokkeerde periode",
            'BOE-0043' => "Onbekende Ubl versie",
            'BOE-0044' => "De aangeboden Ubl is niet compleet",
            'BOE-0045' => "Onbekende fout bij het verwerken van de Ubl",
            'BOE-0046' => "De boeking is gekoppeld aan een Btw aangifte",
            'BOE-0047' => "De boeking is gekoppeld aan een verkoopfactuur",
            'BOE-0048' => "De boeking is gekoppeld aan een inkoopfactuur",
            'BOE-0049' => "De boeking is gekoppeld aan een geldlade",
            'BOE-0050' => "De boeking is gekoppeld aan een bankopdracht",
            'BOE-0051' => "De boeking valt in een periode die door uw accountant is geblokkeerd voor controle of reeds door uw accountant is gecontroleerd",
            'BOE-0052' => "Het Iban nummer van de klant is niet ingevuld, dit is verplicht bij een incasso.",
            'BOE-0053' => "Bij btwregel met te vorderen btw, is een inkoop boekingsregel verplicht",
            'BOE-0054' => "De relatie is verwijderd en staat op nonactief",
            'BOE-0055' => "Incasseren is niet toegestaan voor deze klant.",
            'BOE-0056' => "De omschrijving van de incassomachtiging mag maximaal 50 tekens lang zijn.",
            'BOE-0057' => "Het kenmerk van de incassomachtiging mag maximaal 50 tekens lang zijn.",
            'BOE-0058' => "Het factuurnummer is verplicht en mag maximaal 25 tekens bevatten.",
            'BOE-0060' => "De opgegeven relatie is geen klant.",
            'BOE-0061' => "Er is een niet toegestane grootboekrekening gebruikt.",
            'BOE-0062' => "Btwverlegd mag niet worden gecombineerd met andere btwsoorten.",
            'BOE-0063' => "Er is al een incassomachtiging met het opgegeven kenmerk.",
            'BOE-0064' => "Er is zowel een doorlopende- als een éénmalige incassomachtiging opgegeven.",
            'BOE-0066' => "De opgegeven doorlopende incassomachtiging behoort niet bij de opgegeven klant.",
            'BOE-0067' => "De opgegeven doorlopende incassomachtiging is een éénmalige incassomachtiging.",
            'BOE-0068' => "Het boekstuk mag maximaal 25 tekens lang zijn.",
            'BOE-0069' => "De opgegeven BTW is niet geldig",
            'BOE-0070' => "De opgegeven boekdatum is niet geldig",
            'BOE-0071' => "Een omschrijving mag maximaal 250 tekens lang zijn.",
            'BOE-0075' => "In de boekingsregels mag niet worden geboekt op memoriaal of een balans dagboek",
            'BOE-0076' => "Debet of Credit van een boekingsregel moet 0 zijn",
            'BOE-0077' => "Het dagboek van een boeking kan niet gewijzigd worden",
            'BOE-0078' => "De id kan niet gewijzigd worden",
            'BOE-0079' => "De opgegeven doorlopende incassomachtiging is ingetrokken.",
            'BOE-0080' => "Voor deze klant is boeken op een omzetrekening voor EU niet toegestaan.",
            'BOE-0081' => "Er is geen grootboekrekening aanwezig voor de volgende grootboekfuncties.",
            'BOE-0082' => "Een btw-soort ontbreekt, of komt niet overeen met de btwsoort van de grootboekrekening.",
            'BOE-0083' => "De factuur kan niet worden verwijderd omdat er betalingen zijn.",
            'BOE-0084' => "De omschrijving is verplicht.",
            'BOE-0085' => "De opgegeven grootboekfunctie is niet geldig.",
            'BOE-0086' => "Er is al een grootboek met het opgegeven nummer.",
            'BOE-0087' => "De opgegeven grootboekfunctie mag maar één keer voorkomen en is al door een ander grootboek in gebruik.",
            'BOE-0088' => "De omschrijving bij een grootboekrekening mag maximaal 50 tekens lang zijn.",
            'BOE-0089' => "Het grootboek is niet gevonden",
            'BOE-0090' => "De grootboekfunctie zit niet in de database.",
            'BOE-0091' => "Debet of Credit moet nul zijn",
            'REF-0001' => "Relatie niet gevonden",
            'REF-0002' => "Eén van de te wijzigen velden van de Relatie is niet gevonden",
            'REF-0003' => "Eén van de te wijzigen velden van de Relatie komt meerdere keren voor in uw aanvraag",
            'REF-0004' => "Eén van de tekstvelden is te lang. Een tekstveld mag niet langer zijn dan de waarde van 'MaxLength'",
            'REF-0005' => "Eén van de enum velden is invalide. Een enum veld moet gekozen worden uit één van de waarden in 'PossibleValues'",
            'REF-0006' => "Alleen de extra velden die horen bij de relatiesoort van de relatie kunnen worden aangepast",
            'REF-0007' => "Eén van de waarden van een integer veld kon niet geconverteerd worden naar een integer, een integer is een geheel getal in het bereik [-2147483648, 2147483647]",
            'REF-0008' => "Eén van de waarden van een datetime veld kon niet geconverteerd worden naar een datetime. Het verwachte formaat is yyyy-MM-ddTHH:mm:ss, bijvoorbeeld 1986-05-07T15:32:11",
            'REF-0009' => "Eén van de waarden van een boolean veld kon niet geconverteerd worden naar een boolean",
            'REF-0010' => "Eén van de waarden van een money veld kon niet geconverteerd worden naar een decimal",
            'REF-0011' => "Eén van de waarden van een float veld kon niet geconverteerd worden naar een float, een float moet vallen binnen bereik [-1,79769313486232E+308, 1,79769313486232E+308]",
            'REF-0012' => "Eén van de waarden van een money veld valt buiten het bereik van [-100000000000, 100000000000]",
            'REF-0013' => "Eén van de waarden van een money veld bevat meer dan 4 decimalen.",
            'REF-0014' => "Eén van de waarden van een tekstveld bevat geen string.",
            'REF-0015' => "Eén van de waarden van een datetime veld valt buiten het toegestane bereik van 30-12-1899, 1-1-2401.",
            'REF-0016' => "De input is incompleet, of incorrect. Controleer of de json valide is en de juiste properties bevat",
            'BLG-0001' => "Bijlage niet gevonden.",
            'BLG-0002' => "Dit publicIdentifier bestaat al.",
            'BLG-0003' => "Bijlage kan niet worden opgeslagen.",
            'BLG-0004' => "Inkoopboeking is alleen lezen.",
            'BLG-0005' => "Inkoopboeking niet gevonden.",
            'BLG-0006' => "Bestand is groter dan 10MB.",
            'BLG-0007' => "Geen bestandsnaam opgegeven.",
            'BLG-0008' => "Bijlage is leeg.",
            'BLG-0009' => "Aanvraag is leeg.",
            'BLG-0010' => "De aanvraag bevat geen bijlagen.",
            'BLG-0011' => "Content is leeg.",
            'BLG-0012' => "Thumbnail is leeg.",
            'BLG-0013' => "Content is groter dan 10MB.",
            'BLG-0014' => "Thumbnail is groter dan 10MB.",
            'ART-0001' => "Artikel bestaat niet.",
            'ART-0002' => "Artikelcode is verplicht.",
            'ART-0003' => "Artikelcode is geen nummer.",
            'ART-0004' => "Artikelcode is te lang.",
            'ART-0005' => "Artikelcode bestaat al.",
            'ART-0006' => "Omschrijving is verplicht.",
            'ART-0007' => "Omschrijving is te lang.",
            'ART-0008' => "Artikelomzetgroep is verplicht.",
            'ART-0009' => "Opgegeven artikelomzetgroep bestaat niet.",
            'ART-0010' => "Artikel heeft nog voorraad.",
            'ART-0011' => "Artikel wordt gebruikt in een openstaande order of factuur.",
            'ART-0012' => "Artikel is onderdeel van een recept.",
            'ART-0013' => "Artikel is ingesteld voor grossierkoppeling.",
        ],
    ];

    static public function createFromErrorCode(string $errorCode, int $httpStatusCode = 400): self
    {
        if (!isset(self::API_ERROR_EXCEPTIONS[$httpStatusCode])) {
            throw new SnelstartApiErrorException(sprintf("HTTP error status code unknown, status is '%d'", $httpStatusCode));
        }

        if (!isset(self::API_ERROR_EXCEPTIONS[$httpStatusCode][$errorCode])) {
            throw new SnelstartApiErrorException(sprintf("Error message unknown for code '%s'", $errorCode));
        }

        return new SnelstartApiErrorException(self::API_ERROR_EXCEPTIONS[$httpStatusCode][$errorCode]);
    }
}